using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

// One-shot: builds everything the Pallid Keep needs that cannot be written by
// hand — the mirror pane prefab, its tileset, the test layout, the "Looking Good"
// wave and the map itself — then puts the map in the catalog and points the Mine
// at it. Unity runs this the next time it compiles or regains focus; the version
// guard means bumping the number below and letting Unity recompile rebuilds it in
// place. Tools > Two Knights > Wire Pallid Keep forces a pass.
//
// It exists because of one hard constraint. A sprite's sub-asset fileID is
// GENERATED by the importer, so a .asset that points at one cannot be authored
// offline: writing the YAML by hand produces a map whose backdrop reference looks
// perfectly well-formed in the file and is blank in the editor. Everything here
// resolves its references through AssetDatabase instead, which is the only way
// those ids are ever correct.
//
// Follows CaveLightingWiring for shape and MineCartAssetBuilder for the prefab
// building. Kept apart from both so the castle can be re-cut without touching the
// forest or the mine.
public static class PallidKeepWiring
{
    private const string VersionKey = "TwoKnights.PallidKeepWiring.Version";
    private const int Version = 2;

    // 32 pixels per unit is the project's scale — a 32x32 sprite is one world
    // unit — and both new .aseprite files came in on Unity's default 100. Left
    // alone, the castle backdrop would cover under a third of the arena and a
    // mirror pane would be a third of a unit tall.
    private const float ProjectPixelsPerUnit = 32f;

    private const string CastleArt = "Assets/Graphics/background_castle.aseprite";

    // The mirrors live beside the other game art rather than in palletes/, which
    // holds the palette reference strips. The panes are sprites the game draws,
    // not swatches.
    private const string MirrorArtFolder = "Assets/Graphics/";

    private const string PanePrefabPath = "Assets/Mirror_Pane.prefab";
    private const string ReferenceRail = "Assets/Rail_Horizontal.prefab";

    private const string MirrorFolder = "Assets/Scripts/Mirrors";
    private const string LayoutFolder = MirrorFolder + "/Layouts";
    private const string PaneSetPath = LayoutFolder + "/Keep Panes.asset";
    private const string TestLayoutPath = LayoutFolder + "/Keep Looking Good.asset";

    private const string WaveFolder = "Assets/Scripts/Waves/Castle/LookingGood";
    private const string WavePath = WaveFolder + "/Looking Good.asset";

    private const string MapPath = "Assets/Scripts/Maps/Pallid Keep.asset";
    private const string MinePath = "Assets/Scripts/Maps/The Mine.asset";
    private const string CatalogPath = "Assets/Resources/MapCatalog.asset";

    private const string MapId = "pallid_keep";

    // Panes draw on Background beside the rails rather than on Default with the
    // fighters. They are furniture: a shot passes THROUGH one, so a pane drawn
    // over the arrow crossing it would be reading the mechanic backwards.
    private const string PaneSortingLayer = "Background";
    private const int PaneSortingOrder = 12;

    [InitializeOnLoadMethod]
    private static void QueueIfStale()
    {
        EditorApplication.delayCall += () =>
        {
            if (EditorPrefs.GetInt(VersionKey, 0) >= Version
                && AssetDatabase.LoadAssetAtPath<MapDefinition>(MapPath) != null)
            {
                return;
            }
            Wire();
        };
    }

    [MenuItem("Tools/Two Knights/Wire Pallid Keep")]
    public static void Wire()
    {
        EnsureFolder(LayoutFolder);
        EnsureFolder(WaveFolder);

        // Import settings first: everything below reads sprites back, and a pane
        // sized off a 100-PPU sprite would bake the wrong collider into the prefab
        FixPixelsPerUnit();

        Sprite backdrop = FirstSprite(CastleArt);
        if (backdrop == null)
        {
            Debug.LogError($"[PallidKeepWiring] No sprite at {CastleArt}. The map cannot be built until " +
                           "Unity has imported the backdrop.");
            return;
        }

        GameObject panePrefab = BuildPanePrefab();
        if (panePrefab == null) return;

        MirrorPaneSet paneSet = BuildPaneSet(panePrefab);
        if (paneSet == null) return;

        MirrorLayout layout = BuildTestLayout(paneSet);
        BaseWave wave = BuildWave(layout);
        MapDefinition map = BuildMap(backdrop, wave);

        RegisterInCatalog(map);
        PointTheMineAtIt();

        AssetDatabase.SaveAssets();
        EditorPrefs.SetInt(VersionKey, Version);

        Debug.Log("[PallidKeepWiring] Pallid Keep wired: pane prefab, tileset, test layout, " +
                  "'Looking Good' and the map, and the map is in the catalog.");
    }

    // ---- art ------------------------------------------------------------

    private static void FixPixelsPerUnit()
    {
        int changed = 0;
        if (SetPixelsPerUnit(CastleArt)) changed++;
        foreach (MirrorColor color in System.Enum.GetValues(typeof(MirrorColor)))
        {
            if (SetPixelsPerUnit(ArtPathFor(color))) changed++;
        }

        if (changed > 0)
        {
            Debug.Log($"[PallidKeepWiring] Reimported {changed} .aseprite file(s) at " +
                      $"{ProjectPixelsPerUnit} pixels per unit.");
        }
    }

    private static bool SetPixelsPerUnit(string path)
    {
        AssetImporter importer = AssetImporter.GetAtPath(path);
        if (importer == null)
        {
            Debug.LogWarning($"[PallidKeepWiring] {path} has not been imported yet, so its scale is " +
                             "untouched. Let Unity refresh and run this again.");
            return false;
        }

        var so = new SerializedObject(importer);
        SerializedProperty ppu = so.FindProperty("m_TextureImporterSettings.m_SpritePixelsToUnits");
        if (ppu == null || Mathf.Approximately(ppu.floatValue, ProjectPixelsPerUnit)) return false;

        ppu.floatValue = ProjectPixelsPerUnit;
        so.ApplyModifiedPropertiesWithoutUndo();
        AssetDatabase.WriteImportSettingsIfDirty(path);
        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
        return true;
    }

    private static string ArtPathFor(MirrorColor color)
    {
        return MirrorArtFolder + "mirror_" + color.ToString().ToLowerInvariant() + ".aseprite";
    }

    // Every sprite in an .aseprite, in frame order. The mirrors are two frames
    // (the shimmer); the backdrop is one.
    private static Sprite[] Frames(string path)
    {
        var frames = new List<Sprite>();
        foreach (Object o in AssetDatabase.LoadAllAssetsAtPath(path))
        {
            var sprite = o as Sprite;
            if (sprite != null) frames.Add(sprite);
        }
        frames.Sort((a, b) => string.CompareOrdinal(a.name, b.name));
        return frames.ToArray();
    }

    private static Sprite FirstSprite(string path)
    {
        Sprite[] frames = Frames(path);
        return frames.Length > 0 ? frames[0] : null;
    }

    // ---- the pane -------------------------------------------------------

    // One prefab covers all four colours and both orientations: MirrorPane paints
    // and turns itself from the layout entry. What is baked in here is only what
    // every pane shares — the trigger that catches shots, and a renderer wired to
    // the same lit material the rest of the arena uses.
    private static GameObject BuildPanePrefab()
    {
        Sprite[] green = Frames(ArtPathFor(MirrorColor.Green));
        if (green.Length == 0)
        {
            Debug.LogError($"[PallidKeepWiring] No sprites at {ArtPathFor(MirrorColor.Green)}; " +
                           "the pane prefab is not built.");
            return null;
        }

        GameObject rail = AssetDatabase.LoadAssetAtPath<GameObject>(ReferenceRail);
        SpriteRenderer railRenderer = rail != null ? rail.GetComponent<SpriteRenderer>() : null;

        var root = new GameObject("Mirror_Pane");

        // Kinematic rather than static, with full kinematic contacts on. The
        // knights' arrows are dynamic bodies and would trigger against a bare
        // collider, but the rats' rocks are kinematic, and two kinematic bodies
        // only report each other when one of them asks for it. Without this the
        // castle would swallow enemy fire and pass player fire, which is a very
        // confusing half-working portal.
        var body = root.AddComponent<Rigidbody2D>();
        body.bodyType = RigidbodyType2D.Kinematic;
        body.useFullKinematicContacts = true;
        body.simulated = true;

        var catcher = root.AddComponent<BoxCollider2D>();
        catcher.isTrigger = true;
        catcher.size = new Vector2(1f, 2f); // the tall pane; Configure resizes for wide

        // The art hangs off a child so the ROOT can hold the pane's centre while
        // the sprite keeps the project's pivot-at-the-base convention. MirrorPane
        // sets the offset and the quarter turn from the facing.
        var artHolder = new GameObject("Art");
        artHolder.transform.SetParent(root.transform, false);

        var renderer = artHolder.AddComponent<SpriteRenderer>();
        renderer.sprite = green[0];
        renderer.sharedMaterial = railRenderer != null ? railRenderer.sharedMaterial : null;
        renderer.sortingLayerID = SortingLayer.NameToID(PaneSortingLayer);
        renderer.sortingOrder = PaneSortingOrder;

        var pane = root.AddComponent<MirrorPane>();
        var so = new SerializedObject(pane);
        so.FindProperty("art").objectReferenceValue = renderer;
        so.ApplyModifiedPropertiesWithoutUndo();

        GameObject asset = PrefabUtility.SaveAsPrefabAsset(root, PanePrefabPath);
        Object.DestroyImmediate(root);

        if (asset == null) Debug.LogError($"[PallidKeepWiring] Could not save {PanePrefabPath}.");
        return asset;
    }

    private static MirrorPaneSet BuildPaneSet(GameObject panePrefab)
    {
        MirrorPaneSet set = LoadOrCreate<MirrorPaneSet>(PaneSetPath);

        var so = new SerializedObject(set);
        so.FindProperty("panePrefab").objectReferenceValue = panePrefab;
        so.FindProperty("shimmerInterval").floatValue = 0.18f;

        var colors = so.FindProperty("colors");
        var all = (MirrorColor[])System.Enum.GetValues(typeof(MirrorColor));
        colors.arraySize = all.Length;

        for (int i = 0; i < all.Length; i++)
        {
            string path = ArtPathFor(all[i]);
            Sprite[] frames = Frames(path);
            if (frames.Length == 0)
            {
                Debug.LogWarning($"[PallidKeepWiring] No sprites at {path}. {all[i]} panes will not " +
                                 "be built, and their twins will stand alone.");
            }

            SerializedProperty entry = colors.GetArrayElementAtIndex(i);
            entry.FindPropertyRelative("color").enumValueIndex = (int)all[i];

            SerializedProperty list = entry.FindPropertyRelative("frames");
            list.arraySize = frames.Length;
            for (int f = 0; f < frames.Length; f++)
            {
                list.GetArrayElementAtIndex(f).objectReferenceValue = frames[f];
            }
        }

        so.ApplyModifiedPropertiesWithoutUndo();
        Save(set);
        return set;
    }

    // ---- the test board -------------------------------------------------

    // Eight panes, one pair of every colour, each pair placed to exercise a
    // DIFFERENT turn through the redirect maths. That is what makes this a test
    // rather than a wave: four pairs is too much furniture for anything real (the
    // design doc says two is the normal case), but here the clutter is the point.
    //
    // The arena is roughly 20 x 11.25 world units and the knights stand at about
    // (-2, 0) and (+2, 0), so the middle is kept clear and nothing overlaps
    // anything else.
    private static MirrorLayout BuildTestLayout(MirrorPaneSet paneSet)
    {
        MirrorLayout layout = LoadOrCreate<MirrorLayout>(TestLayoutPath);

        var entries = new[]
        {
            // Aimed at each other: the turn is the identity, so a level shot runs
            // between them and never leaves. High enough to be clear of the knights.
            Entry("loop, right end", MirrorColor.Green, MirrorFacing.Left, 7f, 3.5f),
            Entry("loop, left end", MirrorColor.Green, MirrorFacing.Right, -7f, 3.5f),

            // A tall pane twinned with a wide one: a quarter turn. A shot fired
            // left comes out of the far side travelling up.
            Entry("right angle, in", MirrorColor.Cyan, MirrorFacing.Right, -7f, -3.2f),
            Entry("right angle, out", MirrorColor.Cyan, MirrorFacing.Up, 7f, -3.2f),

            // Twins facing the SAME way: a half turn. A shot in the right-hand
            // pane comes back out of the left-hand one travelling left.
            Entry("reversal, right", MirrorColor.Vermilion, MirrorFacing.Left, 5f, -1.5f),
            Entry("reversal, left", MirrorColor.Vermilion, MirrorFacing.Left, -5f, -1.5f),

            // Two wide panes, one at each edge: the identity again, but across the
            // short axis. Off the top of the arena, back in at the bottom.
            Entry("wrap, top", MirrorColor.Magenta, MirrorFacing.Up, -4f, 5f),
            Entry("wrap, bottom", MirrorColor.Magenta, MirrorFacing.Down, 4f, -5f)
        };

        var so = new SerializedObject(layout);
        so.FindProperty("paneSet").objectReferenceValue = paneSet;
        so.FindProperty("redirect").enumValueIndex = (int)MirrorRedirect.MirrorAboutFacing;

        SerializedProperty panes = so.FindProperty("panes");
        panes.arraySize = entries.Length;
        for (int i = 0; i < entries.Length; i++)
        {
            SerializedProperty pane = panes.GetArrayElementAtIndex(i);
            pane.FindPropertyRelative("label").stringValue = entries[i].label;
            pane.FindPropertyRelative("color").enumValueIndex = (int)entries[i].color;
            pane.FindPropertyRelative("facing").enumValueIndex = (int)entries[i].facing;
            pane.FindPropertyRelative("position").vector2Value = entries[i].position;
        }

        so.ApplyModifiedPropertiesWithoutUndo();
        Save(layout);
        return layout;
    }

    private static MirrorPaneEntry Entry(string label, MirrorColor color, MirrorFacing facing, float x, float y)
    {
        return new MirrorPaneEntry
        {
            label = label,
            color = color,
            facing = facing,
            position = new Vector2(x, y)
        };
    }

    // ---- the wave and the map -------------------------------------------

    private static BaseWave BuildWave(MirrorLayout layout)
    {
        var wave = LoadOrCreate<LookingGood>(WavePath);

        var so = new SerializedObject(wave);
        so.FindProperty("waveName").stringValue = "Looking Good";
        so.FindProperty("waveDescription").stringValue =
            "No enemies. Eight mirrors, one pair of every colour, and a shot to spare.";
        so.FindProperty("weight").floatValue = 1000f;
        so.FindProperty("isUnlocked").boolValue = true;
        so.FindProperty("unlockedAfterXWaves").intValue = -1;
        so.FindProperty("lockedAfterXWaves").intValue = -1;
        so.FindProperty("useEnemyTracking").boolValue = true;
        so.FindProperty("mirrorLayout").objectReferenceValue = layout;
        so.FindProperty("viewingSeconds").floatValue = 120f;
        so.ApplyModifiedPropertiesWithoutUndo();

        Save(wave);
        return wave;
    }

    private static MapDefinition BuildMap(Sprite backdrop, BaseWave wave)
    {
        MapDefinition map = LoadOrCreate<MapDefinition>(MapPath);

        var so = new SerializedObject(map);
        so.FindProperty("mapId").stringValue = MapId;
        so.FindProperty("displayName").stringValue = "Pallid Keep";

        // Open while it is being built out. The Mine already points its gate at
        // this map (see PointTheMineAtIt), so gating it later is one flag rather
        // than a second wiring job.
        so.FindProperty("unlockedByDefault").boolValue = true;
        so.FindProperty("previewImage").objectReferenceValue = backdrop;
        so.FindProperty("lockedHint").stringValue = "Defeat the Millstone";

        SerializedProperty waves = so.FindProperty("waves");
        waves.arraySize = 1;
        waves.GetArrayElementAtIndex(0).objectReferenceValue = wave;

        SerializedProperty folders = so.FindProperty("waveFolders");
        folders.arraySize = 1;
        folders.GetArrayElementAtIndex(0).stringValue = WaveFolder;

        // No bosses yet. WaveManager guards both on null, so an empty gate simply
        // never comes due — the map has one wave and a mechanic to prove.
        so.FindProperty("gateBoss").objectReferenceValue = null;
        so.FindProperty("trueBoss").objectReferenceValue = null;

        // The castle's dead are ordinary residents rather than a late-run
        // escalation, so nothing is held back behind a gate that does not exist.
        so.FindProperty("strongerEnemiesFromWave").intValue = 1;

        SerializedProperty stages = so.FindProperty("stages");
        stages.arraySize = 1;
        SerializedProperty stage = stages.GetArrayElementAtIndex(0);
        stage.FindPropertyRelative("label").stringValue = "Keep";
        stage.FindPropertyRelative("fromWaveNumber").intValue = 1;
        stage.FindPropertyRelative("backdrop").objectReferenceValue = backdrop;

        // Both layers of background_castle.aseprite are composited into the one
        // sprite above — the file is imported Merge Frames, and its second layer
        // covers nearly the whole canvas, so drawing it IN FRONT of the arena
        // would black the fight out.
        stage.FindPropertyRelative("foreground").objectReferenceValue = null;
        stage.FindPropertyRelative("canopy").objectReferenceValue = null;
        stage.FindPropertyRelative("ventureLine").stringValue = string.Empty;

        so.ApplyModifiedPropertiesWithoutUndo();
        Save(map);
        return map;
    }

    // The step that is easy to forget: a map that is not in the catalog never
    // appears in level select, however complete the asset is.
    private static void RegisterInCatalog(MapDefinition map)
    {
        var catalog = AssetDatabase.LoadAssetAtPath<MapCatalog>(CatalogPath);
        if (catalog == null)
        {
            Debug.LogError($"[PallidKeepWiring] No catalog at {CatalogPath}; the map will not appear " +
                           "in level select.");
            return;
        }

        var so = new SerializedObject(catalog);
        SerializedProperty maps = so.FindProperty("maps");

        for (int i = 0; i < maps.arraySize; i++)
        {
            if (maps.GetArrayElementAtIndex(i).objectReferenceValue == map) return; // already listed
        }

        maps.arraySize += 1;
        maps.GetArrayElementAtIndex(maps.arraySize - 1).objectReferenceValue = map;
        so.ApplyModifiedPropertiesWithoutUndo();
        Save(catalog);

        Debug.Log("[PallidKeepWiring] Pallid Keep appended to the map catalog.");
    }

    // Unlocking is a string on the PREVIOUS map, so the castle opens when the
    // Millstone falls. Harmless while the castle is unlocked by default, and it
    // is the half of the wiring that is easy to forget once it is not.
    private static void PointTheMineAtIt()
    {
        var mine = AssetDatabase.LoadAssetAtPath<MapDefinition>(MinePath);
        if (mine == null)
        {
            Debug.LogWarning($"[PallidKeepWiring] No map at {MinePath}; nothing opens the castle.");
            return;
        }

        var so = new SerializedObject(mine);
        SerializedProperty unlocks = so.FindProperty("unlocksMapId");
        if (unlocks.stringValue == MapId) return;

        unlocks.stringValue = MapId;
        so.ApplyModifiedPropertiesWithoutUndo();
        Save(mine);

        Debug.Log("[PallidKeepWiring] The Mine's gate now unlocks the Pallid Keep.");
    }

    // ---- plumbing -------------------------------------------------------

    private static T LoadOrCreate<T>(string path) where T : ScriptableObject
    {
        var asset = AssetDatabase.LoadAssetAtPath<T>(path);
        if (asset != null) return asset;

        asset = ScriptableObject.CreateInstance<T>();
        AssetDatabase.CreateAsset(asset, path);
        return asset;
    }

    private static void Save(Object asset)
    {
        EditorUtility.SetDirty(asset);
        AssetDatabase.SaveAssetIfDirty(asset);
    }

    private static void EnsureFolder(string path)
    {
        if (AssetDatabase.IsValidFolder(path)) return;

        int cut = path.LastIndexOf('/');
        string parent = path.Substring(0, cut);
        string leaf = path.Substring(cut + 1);

        EnsureFolder(parent);
        AssetDatabase.CreateFolder(parent, leaf);
    }
}
